### ISSUE TITLE
some changes to be made

### ISSUE THREAD

**Issue by karmette** [MicrocontrollersDev/Lunar-Client-Alternatives#3]
lunar client 1.7 settings, there's an option to change hit tint color, add aycy's tint colorize thing?
also, remove onhitparticles from 1.7 visuals and make it a separate thing, its not included in 1.7 animations

**Comment by MicrocontrollersDev** [comment]
gg lunar, adding something to the 1.7 amimations tab that has nothing to do with 1.7 animations lol, i'll add that
and for onhitparticles yeah that should be in the particles multiplier one. i'll make that change too

thanks
